### ISSUE TITLE
Ticking entity spawn

### ISSUE THREAD

**Issue by Aabaddon** [LazrProductions/cuffed#1]
in the lastest update for some reason it is trying to cast mobs as players, it constantly makes every single mob that spawns a ticking entity

Cuffed-1.20-1.0.5.jar

[00:40:24] [Server thread/WARN]: Server: §b[Neruina]: §cCaught Ticking Entity [Glow Squid] at position [x=-269, y=27, z=23]. It has been killed.
java.lang.ClassCastException: class net.minecraft.world.entity.GlowSquid cannot be cast to class net.minecraft.world.entity.player.Player (net.minecraft.world.entity.GlowSquid and net.minecraft.world.entity.player.Player are in module minecraft@1.20.1 of loader 'TRANSFORMER' @27dc81be)
	at com.lazrproductions.cuffed.server.CuffedEventServer.playerDied(CuffedEventServer.java:226) ~[Cuffed-1.20-1.0.5.jar%23384!/:1.0.5]
	at com.lazrproductions.cuffed.server.__CuffedEventServer_playerDied_LivingDeathEvent.invoke(.dynamic) ~[Cuffed-1.20-1.0.5.jar%23384!/:1.0.5]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303) ~[forge-1.20.1-47.1.44-universal.jar%23517!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java:1304) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1182) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.world.entity.animal.Squid.m_6469_(Squid.java:183) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.world.entity.GlowSquid.m_6469_(GlowSquid.java:83) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.world.entity.animal.WaterAnimal.m_6229_(WaterAnimal.java:55) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.world.entity.animal.WaterAnimal.m_6075_(WaterAnimal.java:66) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:422) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2259) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.entity.TickOptimizer.mixinextras$bridge$accept$6(TickOptimizer.java) ~[NoSeeNoTick-2.0.0-1.20.1.jar%23452!/:2.0.0-build.9999]
	at net.minecraft.entity.TickOptimizer.wrapOperation$cae000$catchTickingEntities(TickOptimizer.java:538) ~[NoSeeNoTick-2.0.0-1.20.1.jar%23452!/:2.0.0-build.9999]
	at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:62) ~[NoSeeNoTick-2.0.0-1.20.1.jar%23452!/:2.0.0-build.9999]
	at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:25) ~[NoSeeNoTick-2.0.0-1.20.1.jar%23452!/:2.0.0-build.9999]
	at net.minecraft.world.level.Level.m_46653_(Level.java:5041) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23512!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:40:24] [pool-26-thread-4/INFO]: §b[Neruina]: §cCaught Ticking Entity [Glow Squid] at position [x=-269, y=27, z=23]. It has been killed.
[00:40:24] [Render thread/INFO]: [System] [CHAT] §b[Neruina]: §cCaught Ticking Entity [Glow Squid] at position [x=-269, y=27, z=23]. It has been killed.

**Comment by LazrProductions** [comment]
Should be fixed now in version 1.0.6

Sorry about this, hope it didn't cause too many problems.
